#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/jhielson/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/jhielson/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/jhielson/catkin_ws/src/PhD/brainModule/scripts/x86_64/.libs/libnrnmech.so" "$@"
